### ISSUE TITLE
Load videos from storage?

### ISSUE THREAD

**Issue by sokryptk** [lamdev99/gpu_video_flutter_kz#1]
How do I load videos from local storage? 

Android.

**Comment by lamdev99** [comment]
Wow, It is one feature that I want to do in the next version.

Thank you for your comment.

**Comment by sokryptk** [comment]
Hi, turns out I can just pass the video file path to the GPUMoviePreview widget.

Have to add `android.enableDexingArtifactTransform=false
` to gradle.properties though, or else it crashes.

cc @ https://github.com/MasayukiSuda/GPUVideo-android/issues/25

**Comment by lamdev99** [comment]
I faced this issue and I have fixed it by changing RelativeLayout to LinearLayout and adding this line you mentioned 💯

**Comment by lamdev99** [comment]
@krypticallusion  I faced so many difficulties when trying to make this Flutter plugin :))

**Comment by sokryptk** [comment]
Great plugin! Thanks for creating it.

**Comment by lamdev99** [comment]
@krypticallusion You are welcome !!!

**Comment by sokryptk** [comment]
Hi, another thing, how can I specify the dimensions for GPUMoviePreview? I tried to wrap it into a Container and specify a height but it goes fullscreen

**Comment by sokryptk** [comment]
I want to create a squared preview

**Comment by lamdev99** [comment]
after trying to find a solution, I found that this video has been resized to a ratio of 16/9, maybe this code belongs to Android libs which I used in this plugin. I will try to solve it in the next version

**Comment by sokryptk** [comment]
Thanks!
